import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider"
import { Navigation } from "./components/navigation-bar";
import "./globals.css";

import * as React from "react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Navigation />
            {children}
          </ThemeProvider>
        </body>
      </html>
  );
}
