import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider"
import { Navigation } from "./components/navigation-bar";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";

import * as React from "react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col items-end my-2 mr-12">
              <Navigation />
            </div>
            <div className="flex justify-center items-center">
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
      </ClerkProvider>
  );
}
