import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider"
import { Navigation } from "./components/navigation-bar";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

import * as React from "react"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col items-end w-9/10 mt-8 mb-8">
              <Navigation />
            </div>
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
  );
}
